// Q&A assistant backend for docs.regenerativa.earth, served at /api/chat.
//
// POST { question: string, history?: { role: "user"|"assistant", content: string }[] }
// Streams back a minimal SSE protocol: `delta` {text}, `done` {stop_reason}, `error` {message}.
//
// The full agreements corpus (netlify/functions/corpus.md, generated by
// build.sh and packaged via netlify.toml included_files) is sent as the
// system message. OpenAI caches the stable prompt prefix automatically, so
// repeat questions within the cache window pay a discounted input price.
// Requires OPENAI_API_KEY (Netlify env var).

import OpenAI from "openai"
import { getStore } from "@netlify/blobs"
import { readFileSync } from "node:fs"
import { join } from "node:path"

const MODEL = process.env.CHAT_MODEL ?? "gpt-5.4-mini"
const MAX_QUESTION_CHARS = 2000
const MAX_HISTORY_MESSAGES = 12
const MAX_HISTORY_CHARS = 16000
const MAX_ANSWER_TOKENS = 4096
const RATE_LIMIT_PER_MINUTE = 10

// Must stay byte-frozen (no interpolation): the system message is the cached
// prompt prefix, and any change to it invalidates the cache for every request.
const INSTRUCTIONS = `You are the Q&A assistant for the ReGenerativa "Constellation of Agreements" documentation site (docs.regenerativa.earth).

Answer ONLY from the corpus of documents provided below. If the answer is not in the corpus, say so plainly — never invent provisions, obligations, or terms. When you answer, cite the document name(s) you drew from, as given in the "DOCUMENT:" headers, e.g. (Agreement 3 — Stewardship). Quote exact wording when the user asks about specific obligations or definitions.

The corpus is written in English, but ReGenerativa is an Italian organization: always answer in the language the user writes in, translating faithfully from the English source.

Keep answers concise and readable. You provide orientation, not legal advice — for binding interpretations, point the user to the documents themselves and to ReGenerativa. Politely decline questions unrelated to the agreements or to ReGenerativa.`

type HistoryMessage = { role: "user" | "assistant"; content: string }

let corpusCache: string | null = null
function loadCorpus(): string {
  if (corpusCache !== null) return corpusCache
  const candidates = [
    new URL("./corpus.md", import.meta.url), // packaged next to the bundle (production)
    join(process.cwd(), "netlify/functions/corpus.md"), // netlify dev from website/
    join(process.cwd(), "website/netlify/functions/corpus.md"), // netlify dev from repo root
  ]
  for (const candidate of candidates) {
    try {
      corpusCache = readFileSync(candidate, "utf8")
      return corpusCache
    } catch {
      // try next location
    }
  }
  throw new Error("corpus.md not found — was build.sh run before deploying?")
}

let clientCache: OpenAI | null = null
function getClient(): OpenAI {
  if (!process.env.OPENAI_API_KEY) {
    throw new Error("OPENAI_API_KEY is not configured")
  }
  clientCache ??= new OpenAI()
  return clientCache
}

// Best-effort per-IP throttle. Module state resets on cold start and is not
// shared across concurrent instances — the real cost bounds are the input
// caps, the answer token cap, and the daily token budget below.
const requestLog = new Map<string, number[]>()
function rateLimited(ip: string): boolean {
  const now = Date.now()
  const recent = (requestLog.get(ip) ?? []).filter((t) => now - t < 60_000)
  recent.push(now)
  requestLog.set(ip, recent)
  if (requestLog.size > 1000) requestLog.clear()
  return recent.length > RATE_LIMIT_PER_MINUTE
}

// Daily token-budget fuse in Netlify Blobs: caps worst-case daily spend at a
// known amount. Counts prompt + completion tokens (including cached prompt
// tokens) — an over-counting safety fuse, not an accounting system. The
// read-modify-write is not atomic; that imprecision is acceptable here.
function usageKey(): string {
  return `usage/${new Date().toISOString().slice(0, 10)}`
}
async function overDailyBudget(): Promise<boolean> {
  const budget = Number(process.env.CHAT_DAILY_TOKEN_BUDGET)
  if (!budget || !Number.isFinite(budget)) return false
  try {
    const store = getStore("chat-usage")
    const used = Number((await store.get(usageKey())) ?? 0)
    return used >= budget
  } catch (err) {
    console.error("budget check failed", err)
    return false // never let the fuse itself break the chat
  }
}
async function recordUsage(usage: OpenAI.CompletionUsage): Promise<void> {
  try {
    const store = getStore("chat-usage")
    const key = usageKey()
    const used = Number((await store.get(key)) ?? 0)
    const total = usage.prompt_tokens + usage.completion_tokens
    await store.set(key, String(used + total))
  } catch (err) {
    console.error("usage recording failed", err)
  }
}

function jsonResponse(status: number, body: unknown): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  })
}

function sanitizeHistory(raw: unknown): HistoryMessage[] | null {
  if (raw === undefined) return []
  if (!Array.isArray(raw)) return null
  const history: HistoryMessage[] = []
  for (const entry of raw) {
    if (
      typeof entry !== "object" ||
      entry === null ||
      (entry.role !== "user" && entry.role !== "assistant") ||
      typeof entry.content !== "string"
    ) {
      return null
    }
    history.push({ role: entry.role, content: entry.content })
  }
  // Keep only the most recent messages, bounded in count and total size.
  const trimmed = history.slice(-MAX_HISTORY_MESSAGES)
  let chars = 0
  const bounded: HistoryMessage[] = []
  for (let i = trimmed.length - 1; i >= 0; i--) {
    chars += trimmed[i].content.length
    if (chars > MAX_HISTORY_CHARS) break
    bounded.unshift(trimmed[i])
  }
  return bounded
}

export default async (req: Request): Promise<Response> => {
  if (req.method !== "POST") {
    return jsonResponse(405, { error: "Method not allowed" })
  }

  // Soft same-origin check: browsers send Origin on cross-site POSTs, so this
  // blocks other sites' frontends from using the endpoint. It does not stop
  // direct curl calls (Origin can be omitted or spoofed) — the cost guardrails
  // below are the real protection.
  const origin = req.headers.get("origin")
  const allowedOrigins = [
    process.env.URL,
    process.env.DEPLOY_PRIME_URL,
    process.env.DEPLOY_URL,
  ].filter(Boolean)
  if (origin && allowedOrigins.length > 0 && !allowedOrigins.includes(origin)) {
    return jsonResponse(403, { error: "Forbidden" })
  }

  let body: any
  try {
    body = await req.json()
  } catch {
    return jsonResponse(400, { error: "Invalid JSON body" })
  }

  const question = body?.question
  if (typeof question !== "string" || question.trim().length === 0) {
    return jsonResponse(400, { error: "question is required" })
  }
  if (question.length > MAX_QUESTION_CHARS) {
    return jsonResponse(400, { error: `question must be at most ${MAX_QUESTION_CHARS} characters` })
  }
  const history = sanitizeHistory(body?.history)
  if (history === null) {
    return jsonResponse(400, { error: "history must be an array of {role, content} messages" })
  }

  const ip = req.headers.get("x-nf-client-connection-ip") ?? "unknown"
  if (rateLimited(ip)) {
    return jsonResponse(429, { error: "Too many requests — please wait a minute." })
  }
  if (await overDailyBudget()) {
    return jsonResponse(429, {
      error: "The assistant has reached its daily usage limit. Please try again tomorrow.",
    })
  }

  let corpus: string
  let client: OpenAI
  try {
    corpus = loadCorpus()
    client = getClient()
  } catch (err) {
    console.error(err)
    return jsonResponse(500, { error: "The assistant is not configured correctly." })
  }

  let completion: Awaited<ReturnType<typeof client.chat.completions.create>> & AsyncIterable<any>
  try {
    completion = await client.chat.completions.create({
      model: MODEL,
      max_completion_tokens: MAX_ANSWER_TOKENS,
      // Keep reasoning light: this is grounded Q&A over provided text, and
      // reasoning tokens count against max_completion_tokens.
      reasoning_effort: "low",
      stream: true,
      stream_options: { include_usage: true },
      // Helps OpenAI route requests to the same cache shard for prefix reuse.
      prompt_cache_key: "regenerativa-docs",
      messages: [
        { role: "system", content: `${INSTRUCTIONS}\n\n${corpus}` },
        ...history,
        { role: "user", content: question },
      ],
    })
  } catch (err) {
    console.error("openai request failed", err)
    return jsonResponse(502, {
      error: "The assistant is unavailable right now — please try again.",
    })
  }

  const encoder = new TextEncoder()
  const sseBody = new ReadableStream({
    async start(controller) {
      const send = (event: string, data: unknown) => {
        try {
          controller.enqueue(encoder.encode(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`))
        } catch {
          // controller already closed (client disconnected)
        }
      }
      try {
        let usage: OpenAI.CompletionUsage | null = null
        let finishReason: string | null = null
        for await (const chunk of completion) {
          const delta = chunk.choices?.[0]?.delta?.content
          if (delta) send("delta", { text: delta })
          finishReason = chunk.choices?.[0]?.finish_reason ?? finishReason
          if (chunk.usage) usage = chunk.usage
        }
        // cached_tokens under prompt_tokens_details should be non-zero on
        // warm-cache requests; if it stays 0 across consecutive requests, a
        // cache invalidator crept into the prompt prefix.
        console.log("usage", JSON.stringify(usage))
        if (usage) void recordUsage(usage)
        send("done", { stop_reason: finishReason })
      } catch (err) {
        console.error("openai stream error", err)
        send("error", { message: "The assistant hit a problem — please try again." })
      } finally {
        try {
          controller.close()
        } catch {
          // already closed
        }
      }
    },
  })

  return new Response(sseBody, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-store",
      "X-Accel-Buffering": "no",
    },
  })
}

export const config = { path: "/api/chat" }
